### ISSUE TITLE
Cannot use for calls and SMS

### ISSUE THREAD

**Issue by xxirioxx** [Pablito2020/alps_android_device_bq_krillin#1]
Phone says "No service": I cannot make calls or send sms.
Wifi works but I cannot add Google account: it says "access failed" before I insert my email!

**Comment by Pablito2020** [comment]
Okay, will take logcats and fix it soon.
That bug wasn't happening in cm... Seems to be lineage problem.. But will make some changes to ril

Cheers,
Pablito2020

**Comment by xxirioxx** [comment]
Thank you :)
I reinstalled stock 5.0 for now, but I won't configure it because I'll wait for your update ;)

**Comment by Pablito2020** [comment]
Fixed the bug, it was a build.prop problem...
Now that is fixed, this conversation have no sense, so I will close it.
Cheers!
Pablito2020
